apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    run: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - image: hello-world
        name: hello-world
