---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        demotype: nginx-daemonse-dem
    spec:
      containers:
        -
          image: nginx
          name: nginx
